import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.scss";
import { useSession, signIn } from "next-auth/react";
//components
import Footer from "../src/components/Navigation/Footer";
import Profil from "../src/components/Profil";
import { Button } from "../src/components/Ui/Buttons";
//type
import { gitDataList } from "../src/Types/Props";

function Home() {
  const { data: session } = useSession();
  const [profil, setProfil] = useState<Object>({});
  const GIT_HUB_DATA: gitDataList = [{ profil: profil }, { session: session }];
  const [isLoading, setLoading] = useState<Boolean>(false);

  const getData = async () => {
    setLoading(true);
    await fetch(`https://api.github.com/search/users?q=${session.user.email}`)
      .then((res) => res.json())
      .then((data) =>
        fetch(`https://api.github.com/users/${data.items[0].login}`)
      )
      .then((res) => res.json())
      .then(setProfil);
    setLoading(false);
  };

  useEffect(() => {
    if (session) {
      getData();
    }
  }, [session]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Test Technique for Y2M</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {!session && (
          <>
            <div className={styles.home_card}>
              <h1>GitHub Repo Displayer</h1>

              <Button
                onClick={() => {
                  signIn("github");
                }}
                text={"Connection !"}
              />
            </div>
          </>
        )}
        {session && <Profil data={GIT_HUB_DATA} isLoading={isLoading} />}
      </main>
      <Footer />
    </div>
  );
}

export default Home;
